name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: Azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.7
        with:
          inlinescript: |
            az deployment sub create --location "Australia East" --template-file ./arm-templates/resourcegroup.json
