name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: Azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Resource group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope : subscription
          subscriptionId: a9ee9648-5a36-44cc-b898-c54cf9bc37b8
          region: Australia East
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="Australia East"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Storage account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope : resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: a9ee9648-5a36-44cc-b898-c54cf9bc37b8
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=globomanticsarm10071
            location="Australia East"
          deploymentMode: incremental

      - name: Deploy VM
        uses: Azure/arm-deploy@v1
        with:
          scope : resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: a9ee9648-5a36-44cc-b898-c54cf9bc37b8
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword="My$ecureP@ssword!"
          deploymentMode: incremental
